<link rel="stylesheet" href="Pages\Avis\allAvis.css">
<section class="allAvis">
  <!-- <h3 class="header">Avis</h3> -->
  <div class="body">
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
    <?php include 'Pages\Avis\avisWidget.php'; ?>
  </div>
</section>
<script type="text/javascript" src="http://localhost/Departement-math-info/Web/Pages/Avis/allAvis.js"></script>
